#!/bin/bash

BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:46:30 ]] ; then
	i3-nagbar -m "            $(acpi)         "
	#DISPLAY=:0.0 /usr/bin/notify-send "low battery" "$BATTINFO"
fi
