#!/bin/bash

# dims screen brightness


# varble storing value of current screen brightness
bright=$(cat /sys/class/backlight/intel_backlight/brightness)

# decriment the screen value 
val=$(( $bright -500))

# sets new screen value 
echo $val | sudo tee /sys/class/backlight/intel_backlight/brightness


