#!/bin/bash


# for extend screen
xrandr --output HDMI-1 --auto --right-of LVDS-1
#xrandr | grep 'HDMI1 connected' && xrandr --output eDP1 --auto --output HDMI1 --auto --left-of eDP1
#xrandr | grep HDMI-1 |cut -d ' ' -f2 | cut -d ' ' -f1   

# for duplicate or single screen
# xrandr --auto

