#!/bin/bash

xinput set-prop $(xinput list | grep TouchPad | awk '{print $6}'| cut -d '=' -f2 ) 293 1
# device_id=$(xinput list | grep TouchPad | awk '{print $6}'| cut -d '=' -f2 )
# xinput watch-props device_id

# xinput watch-props
# xinput set-prop <device id> <propity number> <1 or 0> 

# xinput set-prop 12 275 1
# Check out the xinput command. xinput list will 

# give you a list of input devices; find the ID of the one 
# which looks like a touchpad. Then do xinput list
# watch-props <device id>, which should tell you what properties 
# you can change for the input device. You should find one 
# called something like Tapping Enabled and a number 
# in parens after it (in my case, it's libinput Tapping Enabled 
# (276). Finally, run xinput set-prop <device id> <property id> 1, and tapping should work.

# To make the change permanent, find a way to run that command on 
# startup. One way would be to add exec xinput set-prop <device id> <property id> 1 to ~/.i3/config.

