# Shell variables
# Generated by 'wal'
wallpaper='/home/wheatley/.config/wpg/wallpapers/7mJZ5ct.jpg'

# Special
background='#151f19'
foreground='#fcfffd'
cursor='#e4e8e5'

# Colors
color0='#151f19'
color1='#64B3B6'
color2='#94B8B6'
color3='#94C7CA'
color4='#B4D2D4'
color5='#CDDBD9'
color6='#E4DFD7'
color7='#e4e8e5'
color8='#25372c'
color9='#6ff9fe'
color10='#aaffff'
color11='#a9ffff'
color12='#d0ffff'
color13='#ddffff'
color14='#ffffde'
color15='#fcfffd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
